{
 "title": "Servers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   {
    "name": "ServerName",
    "label": "Server Name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "live logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"$ServerName\"} |= ``"
    }
   ]
  },
  {
   "title": "débit de logs",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({host=\"$ServerName\"} [1m])"
    }
   ]
  },
  {
   "title": "Logs ERROR",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"$ServerName\"} |= `error`"
    }
   ]
  },
  {
   "title": "Logs WARN",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"$ServerName\"} |= `warn`"
    }
   ]
  },
  {
   "title": "Logs INFO",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"$ServerName\"} |= `info`"
    }
   ]
  },
  {
   "title": "Nombre d'erreurs sur 5 min",
   "type": "stat",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({host=\"$ServerName\"} |= `error` [5m])"
    }
   ]
  }
 ]
}